apiVersion: v1
kind: Pod
metadata:
  name: httpprobe
spec:
  containers:
  - name: httpprobe
    image: kadanli/livep:v0.1
    ports:
      - containerPort: 8080
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /liveProbe
        port: 8080
      initialDelaySeconds: 25
      failureThreshold: 2
      successThreshold: 1
      periodSeconds: 5
      timeoutSeconds: 3
